version: 0

exclude:
  - ^hr-locks/.*

environments:
  - id: python312
    ecosystem:
      language: python
      version: "3.12"
    dependencies:
      - black
      - mypy

  - id: python-sep
    ecosystem:
      language: python
      version: "3.12"
    dependencies:
      - ruff
      - pre-commit-hooks

  - id: node
    ecosystem:
      language: node
      version: "21.7.1"
    dependencies:
      - prettier

hooks:
  - id: check-case-conflict
    environment: python-sep
    command: check-case-conflict
    read_only: true

  - id: check-merge-conflict
    environment: python-sep
    command: check-merge-conflict
    read_only: true
    types: [text]

  - id: python-debug-statements
    environment: python-sep
    command: debug-statement-hook
    read_only: true
    types: [python]

  - id: detect-private-key
    environment: python-sep
    command: detect-private-key
    read_only: true
    types: [text]

  - id: end-of-file-fixer
    environment: python-sep
    command: end-of-file-fixer
    types: [text]

  - id: trailing-whitespace-fixer
    environment: python-sep
    command: trailing-whitespace-fixer
    types: [text]

  - id: ruff
    environment: python-sep
    command: ruff
    args: [check, --force-exclude, --fix]
    types: [python]

  - id: black
    environment: python312
    command: black
    types: [python]

  - id: prettier
    environment: node
    command: prettier
    types: [markdown]
    args:
      - --write
      - --ignore-unknown
      - --parser=markdown
      - --print-width=88
      - --prose-wrap=always
