name: Publish Documentation

on:
  push:
    branches:
      - main
    tags:
      - '**'

env:
  COLUMNS: 120

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout and prepare git.
      - name: checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - uses: actions/checkout@v4
      - name: Set git credentials
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      # Setup uv and install dependencies.
      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - run: uv venv --python=3.13
      - run: >-
          uv pip install
          --require-hashes
          --no-deps
          -r requirements-docs.txt
      - run: uv pip install . --no-deps
      - run: uv pip check

      - if: "github.ref == 'refs/heads/main'"
        run: uv run mike deploy --branch=gh-pages dev --push

      - if: "startsWith(github.ref, 'refs/tags/')"
        id: check-version
        uses: samuelcolvin/check-python-version@v4.1
        with:
          version_file_path: 'src/goose/_version.py'
          skip_env_check: true

      - if: "startsWith(github.ref, 'refs/tags/') && !fromJSON(steps.check-version.outputs.IS_PRERELEASE)"
        run: uv run mike deploy --branch=gh-pages ${{ steps.check-version.outputs.VERSION_MAJOR_MINOR }} latest --update-aliases --push
