# This is a reusable workflow that's meant to be the canonical way of running goose in
# Github Actions workflows. See README for an example of how to use this in your
# workflows.

on:
  workflow_call:
    inputs:
      goose-version:
        type: "string"
        required: false
        default: "latest"

jobs:
  goose-run:
    name: Run goose checks
    runs-on: ubuntu-latest
    env:
      cache-directory: ~/.goose-cache
    steps:
      - uses: actions/checkout@v4
      - name: Environment cache
        uses: actions/cache@v4
        with:
          path: ${{ env.cache-directory }}
          key: ${{ runner.os }}-goose-${{ hashFiles('.goose/**/manifest.json') }}
          restore-keys: |
            ${{ runner.os }}-goose
      - name: Create cache directory
        run: |
          mkdir -p  ${{ env.cache-directory }}
      - name: goose run
        run: >-
          docker run --rm
          -v ${PWD}:/wd
          -v  ${{ env.cache-directory }}:/home/nonroot/.cache
          --user $(id --user):$(id --group)
          ghcr.io/antonagestam/goose:${{ inputs.goose-version }}
          run --select=all --delete-orphan-environments
